
# -> all the users
GET localhost:3000/user/all

GET localhost:3000/user/ddfaed52-f168-4644-926c-41538a790bb2

# -> seed all the users at seed.json
POST localhost:3000/user/lot
Content-Type: application/json

< ./seed.json

POST localhost:3001

POST localhost:3000/user/
Content-Type: application/json

< ./one.json
# -> trunctate

DELETE localhost:3000/user/all
